-- AUTO
CREATE TABLE EMPLOYEE_AUTO(ROLL_NO BIGINT, NAME VARCHAR, EMAIL VARCHAR, AGE NUMBER, SALARY DECIMAL);
CREATE SEQUENCE HIBERNATE_SEQUENCE;
ALTER TABLE EMPLOYEE_AUTO MODIFY ROLL_NO BIGINT NOT NULL;  
ALTER TABLE EMPLOYEE_AUTO ADD PRIMARY KEY (ROLL_NO);
ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART WITH 1001;
DROP SEQUENCE HIBERNATE_SEQUENCE;

-- IDENTITY
ALTER TABLE TABLE_NAME ALTER COLUMN COLUMN_NAME RESTART WITH 1001;


-- SEQUENCE
CREATE TABLE EMPLOYEE_SEQUENCE(EMP_NO BIGINT PRIMARY KEY, NAME VARCHAR, EMAIL VARCHAR, AGE NUMBER, SALARY DECIMAL);
CREATE SEQUENCE SEQ_EMPLOYEE_SEQUENCE_EMP_NO;