CREATE TABLE STUDENT (ROLL_NO NUMBER, NAME VARCHAR, IS_GRADUATE BOOLEAN);

CREATE TABLE EMPLOYEE(
EMP_NO NUMBER PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR,
EMAIL VARCHAR,
AGE NUMBER,
SALARY DECIMAL
);



--One to One Mapping
CREATE TABLE CAR (
MODEL_NBR BIGINT AUTO_INCREMENT PRIMARY KEY,
MODEL_NAME VARCHAR,
COMPANY VARCHAR,
CAR_ENGINE_NBR BIGINT
);

CREATE TABLE ENGINE(
ENGINE_NBR BIGINT AUTO_INCREMENT PRIMARY KEY,
MILEAGE DECIMAL,
SPEED NUMBER
);

ALTER TABLE CAR 
ADD CONSTRAINT CAR_ENGINE_NBR_FK 
FOREIGN KEY (CAR_ENGINE_NBR) REFERENCES ENGINE(ENGINE_NBR);